### ISSUE TITLE
Remove sniffs in favor of build-in ones

### ISSUE THREAD

**Issue by aik099** [joomla/coding-standards#104]
The following sniffs can be removed in favor of one of core PHP_CodeSniffer sniffs, that do the same:
- ElseIfDeclarationSniff
- LowerCaseConstantSniff (removed in #101)
- CastSpacingSniff (removed in #101)
- SpaceAfterCastSniff (doesn't this conflict with above sniff?)
- ConcatenationSpacingSniff
- DisallowSpaceIndentSniff (removed in #101)
- SuperfluousWhitespaceSniff
- SemicolonSpacingSniff (removed in #101)

**Comment by photodude** [comment]
The following can also be eliminated since they are exact duplicates of the core PHP_CodeSniffer sniffs
- MemberVarSpacingSniff
- ObjectOperatorIndentSniff

**Comment by photodude** [comment]
On review, The Joomla  ElseIfDeclarationSniff is different from the source and should not be removed
There is a small but important difference.

Joomla standard | Squiz standard
:-------------: | :-------------:
|Usage of ELSE IF is not allowed; use ELSEIF instead  | Usage of ELSEIF not allowed; use ELSE IF instead |

**Comment by aik099** [comment]
> On review, The Joomla ElseIfDeclarationSniff is different from the source and should not be removed
There is a small but important difference.

Are you sure, that there is no other elseif sniff in non-Squiz standard? I've found https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/PSR2/Sniffs/ControlStructures/ElseIfDeclarationSniff.php , but I needed to change it from warning to error in `ruleset.xml` to get desired result (https://github.com/aik099/CodingStandard/blob/master/CodingStandard/ruleset.xml#L188-L190).

**Comment by photodude** [comment]
@aik099 Thanks, I totally missed that elseif sniff in the PSR2 standard.

**Comment by photodude** [comment]
On review of Squiz.Strings.ConcatenationSpacing there is a difference

Joomla standard | Squiz standard
:-------------: | :-------------:
Concat operator must be preceeded/followed by one space | Concat operator must not be surrounded by spaces

I was unable to find any other relevant ConcatenationSpacing sniffs in the other PHPCS standards.

**Comment by aik099** [comment]
> I was unable to find any other relevant ConcatenationSpacing sniffs in the other PHPCS standards.

I can propose sniff of my own making: https://github.com/aik099/CodingStandard/blob/master/CodingStandard/Sniffs/Strings/ConcatenationSpacingSniff.php

> On review of Squiz.WhiteSpace.SuperfluousWhitespace I find the Joomla standard includes an additional registrar and methods for T_CLOSE_CURLY_BRACKET.

Then just extend that sniff and add missing token. I thought that that sniff just removes trailing whitespaces, but then I don't understand why it needs any special tokens to operate with.

**Comment by photodude** [comment]
I have re-reviewed the Squiz.Strings.ConcatenationSpacing, I agree with this change since in PHPCS 2.3.x you can pass in a value for "spacing" and get the desired space before/after result from the ruleset.

I have re-reviewed Squiz.WhiteSpace.SuperfluousWhitespace, the Joomla sniff use of T_CLOSE_CURLY_BRACKET seems to be looking for a CURLY_BRACKET or semi-colon before the eolChar \n as a condition for the end of the file. Since this seems to be a duplication or confliction with the end of line sniff. As such I am in favor of replacing the custom sniff with Squiz.WhiteSpace.SuperfluousWhitespace. 

On re-review of various included standards, rather than replacing with Squiz.Formatting.SpaceAfterCast; the correct replacement for the custom sniff would be Generic.Formatting.SpaceAfterCast

**Comment by photodude** [comment]
@mbabker This can be closed with the merge of #109

**Comment by mbabker** [comment]
Sounds good.  Let's leave the 1.x structure in a "minimal maintenance" type of state.
