### ISSUE TITLE
Coding Standard for Coding Standards

### ISSUE THREAD

**Issue by mbabker** [joomla/coding-standards#114]
Most of the file structures match the source they were copied from, meaning our coding standard files don't even follow our coding standard.  On one hand, this makes it a bit easier to follow along with upstream changes, but on the other it's just another inconsistency.

Since we're working on updating everything for PHPCS 2 anyway, any thoughts on tacking onto that TODO list "make coding standard sniffs align with our standard"?

**Comment by wilsonge** [comment]
That would make a lot of sense

**Comment by rdeutz** [comment]
Whatever, would be great to move to 2.x so that we can do some automatic changes. Any idea what is the best way to do it. Should we update what we have or just starting with an existing 2.x sniff and changing the bits we need to change?

**Comment by mbabker** [comment]
Take a look at #109 - @photodude has done a lot of effort to get things updated and I finally carved out a little time to look things over and test it out.

**Comment by rdeutz** [comment]
so we need to test more, sounds great, I hope I find some time next week to test

**Comment by photodude** [comment]
I would agree to "tacking onto that TODO list "make coding standard sniffs align with our standard" 
I think we should make a real effort to include references to the source sniffs the custom sniffs are based on. Some of the existing custom sniffs were 1-to-1 copies from the source standard sniffs and a few used different naming even though they were just copies. It's been an interesting process of trying to puzzle out what the sniffs were to try to determine if they could be eliminated since they were just a copy of an existing sniff; or what they were based on to see what modifications would be needed to migrate to phpcs2.
