### ISSUE TITLE
VS Code IDE autoformatters

### ISSUE THREAD

**Issue by brianteeman** [joomla/coding-standards#178]
Is anyone able to help with what it takes to create an IDE autoformatter for Visual Studio Code?

**Comment by zero-24** [comment]
Ah I would be interested too :+1: 

But i guess this should help:
https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs
&&
`settings: editor.formatOnType: true`

But i have not tryed it yet.

**Comment by brianteeman** [comment]
Yes I started there but then we need the Joomla specific stuff. I think

**Comment by zero-24** [comment]
I'nt the file we need this: https://github.com/joomla/coding-standards/blob/master/Joomla/ruleset.xml ?

**Comment by photodude** [comment]
@zero-24 that is just the PHPCS 2.x ruleset, it only applies to PHPCS 2.x. VS will need a VS specific solution, just like the [one specific to PHP storm's set up](https://github.com/joomla/coding-standards/blob/master/Joomla/IDE/joomla_phpstorm.xml) or the [one for eclipse](https://github.com/joomla/coding-standards/blob/master/Joomla/IDE/eclipse_pdt3_formatter.xml) etc

It's different from the linter plugins for VS or phpstorm than connects into PHPCS. 
see https://code.visualstudio.com/docs/getstarted/settings

What would need to be created is a `settings.json` for VS which is configured for PHP Language specific editor settings

I will assume that the configuration will meet some basics of the Joomla code style but will not meet the full code style (the same is true of all the IDE formatters).

**Comment by photodude** [comment]
Just came across this guide https://github.com/tommcfarlin/phpcs-wpcs-vscode

once you have PHPCS and the Joomla standard installed, edit your VS settings.json (easy now that the alpha release is out on composer... but note there is a small bug in the current alpha release that has been fixed in the master branch.

```json
// Place your settings in this file to overwrite the default settings
{
    "phpcs.enable":   true,
    "phpcs.standard": "Joomla",
}
```
And this will enable PHPCS and will also tell it to use the Joomla standard

note: for the CMS it's recommended to use the example ruleset for the CMS to ignore certain rules and folders (especially ignoring the vendor/3rd-party-code folders)
to install one of the included example rulesets
```cmd
./vendor/bin/phpcs --config-set installed_paths /path/to/project/vendor/joomla//coding-standards/Joomla/ExampleRulesets
```
then edit your VS settings.json

```json
{
    "phpcs.enable":   true,
    "phpcs.standard": "Joomla-CMS",
}
```

**Comment by brianteeman** [comment]
Cool I give that a try next week - thanks!!!

**Comment by photodude** [comment]
You are welcome. I also forked and attempted to rewrite the guide for working the Joomla CS
https://github.com/photodude/phpcs-vscode

**Comment by tonypartridge** [comment]
@brianteeman did you give it a try? Can this be closed now?

**Comment by brianteeman** [comment]
its on my very long todo list still but i guess it can be closed
