### ISSUE TITLE
False negative when method name is same as constructor

### ISSUE THREAD

**Issue by eddieajau** [joomla/coding-standards#40]
This is a probably a hang over from the PHP 4 days. A class that has a method with the same name as the class is throwing a code-style error.  For example:

https://github.com/joomla/joomla-framework/blob/staging/src/Joomla/Twitter/Search.php#L40

Can we just remove this check?

**Comment by photodude** [comment]
@mbabker I believe this issue should be close considering the PHP 7 requirements

in PHP7 
>PHP 4 style constructors (methods that have the same name as the class they are defined in) are deprecated

As for the other error listed here in the comments `The use of function delete() is forbidden; use unset() instead` that is related to the sniff that checks for forbidden function names. The [Generic.PHP.ForbiddenFunctions](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Sniffs/PHP/ForbiddenFunctionsSniff.php) Sniff actively 
>Discourages the use of alias functions that are kept in PHP for compatibility with older versions. Can be used to forbid the use of any function name.

since we don't supply our own list to the sniff we only forbid the two default function names in the sniff  `delete()` and `sizeof()`
(if the Forbidden Functions name list is something to change a new issue should be opened)
